----1. From the following table, write a SQL query to select all the salespeople. Return salesman_id, name, city, commission with the percent sign (%)
select salesman_id, name, city, commission * 100 as 'percent', '%' as 'percentage_sign' from [W3Resource].[Inventory].[Salesman]

select salesman_id, name, city, concat(cast(commission * 100 as varchar), '%') as 'percentage_sign' from [W3Resource].[Inventory].[Salesman]
----- did it through some research 

----2. From the following table, write a SQL query to find the number of orders booked for each day. 
--Return the result in a format like "For 2001-10-10 there are 15 orders".".   

select 'For' as _ , ord_date as _ , 'there are' as _, COUNT(ord_no) as _ , 'orders' as _ from [W3Resource].[Inventory].[Orders]
group by ord_date
---select * from [W3Resource].[Inventory].[Orders]

----3. From the following table, write a SQL query to find all the orders. Sort the result-set in ascending order by ord_no. Return all fields. 
select * from [W3Resource].[Inventory].[Orders]
order by ord_no asc


----4. From the following table, write a SQL query to find all the orders. Sort the result-set in descending order by ord_date. Return all fields. 
select * from [W3Resource].[Inventory].[Orders]
order by ord_date asc   

-----From the following table, write a SQL query to find all the orders. Sort the result-set in descending order by ord_date and purch_amt. Return all fields.  

select * from [W3Resource].[Inventory].[Orders]
order by ord_date, purch_amt desc  

----6. From the following table, write a SQL query to find all the customers. Sort the result-set by customer_id. Return cust_name, city, grade. 

select cust_name, city, grade from [W3Resource].[Inventory].[Customer]
order by customer_id asc 

----7. From the following table, write a SQL query that calculates the maximum purchase amount generated by each salesperson for each order date.
---Sort the result-set by salesperson id and order date in ascending order. Return salesperson id, order date and maximum purchase amount. 

select salesman_id, ord_date, MAX(purch_amt) from [W3Resource].[Inventory].[Orders]
group by salesman_id, ord_date
order by salesman_id 


----8. From the following table, write a SQL query to find all the customers.
---Sort the result-set in descending order on 3rd field. Return customer name, city and grade. 

select cust_name, city, grade from [W3Resource].[Inventory].[Customer]
order by grade desc 


----9. From the following table, write a SQL query that counts the unique orders and the highest purchase amount for each customer. 
----Sort the result-set in descending order on 2nd field. Return customer ID, number of distinct orders and highest purchase amount by each customer.

select customer_id, MAX(purch_amt) as 'max', COUNT( distinct ord_no) as 'unique' from [W3Resource].[Inventory].[orders]
group by customer_id, ord_no


----10. From the following table, write a SQL query to calculate the summation of purchase amount,
---total commission (15% for all salespeople) by each order date. Sort the result-set on order date. Return order date, summation of purchase amount and commission.

select ord_date, SUM(purch_amt) as 'total_sales', '15%' as 'commission' from [W3Resource].[Inventory].[Orders]
group by ord_date
order by ord_date 
